# Generated by Django 5.0.6 on 2024-05-29 10:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_comment_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='project_id',
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(default=django.utils.timezone.now, help_text='Project to which the issue belongs', on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='project.project', verbose_name='related project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID of the project', unique=True, verbose_name='project ID'),
        ),
    ]
