# Generated by Django 5.0.6 on 2024-06-05 12:55

import project.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_comment_author_alter_issue_assigned_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=models.SET(project.models.get_admin_user), related_name='comment_authors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User assigned to the issue', null=True, on_delete=models.SET(project.models.get_admin_user), related_name='assigned_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='author',
            field=models.ForeignKey(help_text='Issue author', on_delete=models.SET(project.models.get_admin_user), related_name='issue_authors', to=settings.AUTH_USER_MODEL, verbose_name='issue author'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contributor_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(project.models.get_admin_user), related_name='owned_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
