# Generated by Django 5.0.6 on 2024-06-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_comment_author_alter_issue_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_id',
            field=models.PositiveIntegerField(editable=False, help_text='Unique ID of the issue', unique=True, verbose_name='issue ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(editable=False, help_text='Unique ID of the project', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='project ID'),
        ),
    ]
