# Generated by Django 5.0.6 on 2024-06-19 13:31

import django.db.models.deletion
import project.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_issue_issue_id_alter_project_project_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contributor_owner',
        ),
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(project.models.get_admin_user), related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire du projet'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='project',
            field=models.ForeignKey(help_text='Projet auquel le contributeur contribue', on_delete=django.db.models.deletion.CASCADE, related_name='contributor_relationship', to='project.project'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text="Utilisateur assigné à l'issue", null=True, on_delete=models.SET(project.models.get_admin_user), related_name='assigned_issues', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur assigné'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='author',
            field=models.ForeignKey(help_text="Auteur de l'issue", on_delete=models.SET(project.models.get_admin_user), related_name='issue_authors', to=settings.AUTH_USER_MODEL, verbose_name="auteur de l'issue"),
        ),
        migrations.AlterField(
            model_name='issue',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date de création'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(help_text="Description de l'issue"),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_id',
            field=models.PositiveIntegerField(editable=False, help_text="Identifiant unique de l'issue", unique=True, verbose_name="ID de l'issue"),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Basse'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute')], default='MEDIUM', help_text="Priorité de l'issue", max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(help_text="Projet auquel l'issue appartient", on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='project.project', verbose_name='projet associé'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('TO_DO', 'À faire'), ('IN_PROGRESS', 'En cours'), ('FINISHED', 'Terminée')], default='TO_DO', help_text="Statut de l'issue", max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('BUG', 'Bogue'), ('FEATURE', 'Fonctionnalité'), ('TASK', 'Tâche')], default='BUG', help_text="Catégorie de l'issue", max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(help_text="Titre de l'issue", max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(help_text='Contributeurs du projet', related_name='contributions', through='project.Contributor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date de création'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Description du projet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Nom du projet', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(editable=False, help_text='Identifiant unique du projet', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='project ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend'), ('iOS', 'iOS'), ('Android', 'Android')], help_text='Type de projet', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='date de mise à jour'),
        ),
    ]
