# Generated by Django 5.0.6 on 2024-06-19 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_project_contributor_owner_project_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='uuid',
            new_name='comment_id',
        ),
    ]
