# Generated by Django 5.0.6 on 2024-06-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_rename_uuid_comment_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', help_text="Priorité de l'issue", max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('TO_DO', 'to do'), ('IN_PROGRESS', 'in_progress'), ('FINISHED', 'finished')], default='TO_DO', help_text="Statut de l'issue", max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('BUG', 'Bug'), ('FEATURE', 'Feature'), ('TASK', 'Task')], default='BUG', help_text="Catégorie de l'issue", max_length=20),
        ),
    ]
